### ISSUE TITLE
2022 level1 독서모임 우아한책벌레들 :heart:

### ISSUE THREAD

**Issue by intae92** [woowacourse-study/2022-woowahan-bookworms#145]
@soyi47 소피아
@kkojae91 꼬재
@kbsat 로마
@skullkim 스컬
@sanaandmomo 아놀드
@shindong96 아스피
@sinb57 이프
@hyunrrr 조시
@intae92 코카콜라
@moonheekim0118 호프

<img width="940" alt="2022-level-1-woowahan-bookworms" src="https://user-images.githubusercontent.com/56149367/162150939-ec2f2557-8f5d-49bc-8184-8dff689a12d1.png">

**Comment by sanaandmomo** [comment]
1빠 
아 머리 좀 감고 세수만이라도 할 걸
